feature file for the add contact created
SagarGi/FeatureFiles pull request #14
Opened 2022-10-12 16:06 UTC by ritaadhikari

### Description 
Here the different scenarios of the add contact feature has been added to the addcontact.feature file.

### Issues addressed:
https://github.com/SagarGi/FeatureFiles/issues/4

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Then the user should be logged in to the homepage
background does not contains `When` and `Then` step but only `Given` step

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Given the  user  navigated to the login page
```suggestion
        Given the user has navigated to the login page
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Scenario:add to contacts with personal contact type
```suggestion
        Scenario: Add to contacts with personal contact type
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Given the user is navigated to the home page
```suggestion
        Given the user has navigated to the home page
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        When the user submit name with "name" and email with "valid email" and chooses the contact type as "personal"
use `datatable`

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Then the user info will be added to the contact list  with the personal  badge
which user to check ? may be give user information that has been added to contact

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/login.feature
> +        When  the user enters the valid credentials with email "valid email" and Password "valid password"S
```suggestion
        When  the user enters the valid credentials with email "valid email" and Password "valid password"
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Scenario:add to contacts with professional contact type
```suggestion
        Scenario: Add to contacts with professional contact type
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Then the user info will be added to the contact list  with the professional badge
follow same as i have commented

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Given a user has navigated to the homepage
```suggestion
        Given the user has navigated to the homepage
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        When the user enters with a "<email>"
```suggestion
        When the user enters invalid email "<email>"
```

2022-10-13 14:45 UTC, SagarGi commented on Features2/tests/features/addcontact.feature
> +        Then the user will thrown a "<message>"
huh? user will thrown? please make a valid step

2022-10-17 05:32 UTC, kiranadh1452 requested changes

2022-10-17 05:32 UTC, kiranadh1452 commented on Features2/tests/features/addcontact.feature
> +        | risahgdgajda36gmail.com | Please enter an email address|
Use formatting.

2022-10-17 05:32 UTC, kiranadh1452 commented on Features2/tests/features/addcontact.feature
> +        And  the user was logged in to the homepage
Make this a single step.

2022-10-18 03:56 UTC, kiranadh1452 approved these changes

2022-10-18 03:56 UTC, merged