User registration feature file by rita
SagarGi/FeatureFiles pull request #15
Opened 2022-10-12 17:01 UTC by ritaadhikari

### Description
New feature file userRegistration.feature created for the  Registration feature and different scenarios of the registration has been built.

###Issues :
https://github.com/SagarGi/FeatureFiles/issues/2

2022-10-13 14:47 UTC, SagarGi commented
@ritaadhikari Please make one PR for one issue you have added `Add contact ` issue in user registration PR

2022-10-17 05:28 UTC, kiranadh1452 requested changes

2022-10-17 05:28 UTC, kiranadh1452 commented on Features2/tests/features/userRegistration.feature
> +
Use formatting.

2022-10-17 05:28 UTC, kiranadh1452 commented on Features2/tests/features/userRegistration.feature
> +            When the user enters the name with "name" and email with "valid email" and password with "password" and confirm password with "password"
You have used some actual data in the example table in line no. 19. Use similar values here.

2022-10-17 07:13 UTC, kiranadh1452 approved these changes

2022-10-17 07:13 UTC, merged