NewUserRegistration feature file added
SagarGi/FeatureFiles pull request #16
Opened 2022-10-13 08:53 UTC by Samikshap85

### Description
>This PR add feature file for new user registration
### Related Issues
https://github.com/SagarGi/FeatureFiles/issues/2

2022-10-13 10:12 UTC, kiranadh1452 requested changes

2022-10-13 10:12 UTC, kiranadh1452 commented on Features1/tests/features/login.feature
> +Scenario
```suggestion
        |abc@gmail   |hyyy    |                                          |

```

2022-10-13 10:12 UTC, kiranadh1452 commented on Features1/tests/features/newUserRegistration.feature
> +    When the user enter "Name" ,valid "validEmailAddress", "validPassword" and confirm password as "validPassword"
Use actual names and proper email formats.

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +    So that i can have the access of homepage
```suggestion
    So that i can use the contact fox app
```

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +            When the user enter "Name" ,valid "validEmailAddress", "validPassword" and confirm password as "validPassword"
use `data table`

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +            Then the error "<message>" should pop
```suggestion
            Then the error message "<message>" should pop up on the webUI
```

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +            When the user enters name as "<name>" email address as "<invalidemail>" and password as "<password>" and confirm password as "<password>"
use `datatable`

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +            When the user enters name as "<name>" email address as "<validemail>" and password as "<invalidpassword>" and confirm password as "<invalidpassword>"
use `datatable`

2022-10-13 14:36 UTC, SagarGi commented on Features1/tests/features/newUserRegistration.feature
> +            When the user enters name as "<name>" email address as "<validemail>" and password as "<password>" and confirm password as "<confirmpassword>"
use `datatable`

2022-10-18 04:14 UTC, SagarGi approved these changes

2022-10-18 04:14 UTC, merged