Add contact feature file
SagarGi/FeatureFiles pull request #18
Opened 2022-10-13 12:59 UTC by Samikshap85

### description
>This PR contain add contact feature files 

### Issues
https://github.com/SagarGi/FeatureFiles/issues/4

2022-10-13 14:19 UTC, SagarGi commented
@Samikshap85 make separate PR for each issue. You have PR title `Add contact` and has issue linked related to Adding contact. Why are you adding user registration feature here?

2022-10-14 04:00 UTC, kiranadh1452 requested changes

2022-10-14 04:00 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +    Background: Given the user have navigated to the homepage
```suggestion
    Background:
      Given the user have navigated to the homepage  
```

2022-10-14 04:00 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +            And click "Add contact" button
```suggestion
            And clicks "Add contact" button
```

2022-10-14 04:00 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +            Then added contacts should be displayed
State explicitly which contact should be displayed.

2022-10-14 04:00 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +
You could try modifying this so as to cover all invalid cases (not only invalid emails.)

2022-10-17 06:05 UTC, kiranadh1452 requested changes

2022-10-17 06:05 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +        Given the user have navigated to the homepage
```suggestion
        Given the user has navigated to the homepage  
```

2022-10-17 06:05 UTC, kiranadh1452 commented on Features1/tests/features/addContact.feature
> +        Given the user have navigated to the homepage
```suggestion
        Given the user has navigated to the homepage  
```

2022-10-18 04:22 UTC, kiranadh1452 approved these changes

2022-10-18 05:33 UTC, merged