Delete Contact Feature File
SagarGi/FeatureFiles pull request #19
Opened 2022-10-13 13:30 UTC by Samikshap85

### description 
>This PR contains delete contact feature file

### issues
https://github.com/SagarGi/FeatureFiles/issues/5

2022-10-13 14:17 UTC, SagarGi commented on Features1/tests/features/deleteContact.feature
> +        When  the user click "delete" botton
how would you know which `delete` button to click if there are multiple contacts? may be give user information which one to delete.

2022-10-13 14:17 UTC, SagarGi commented on Features1/tests/features/deleteContact.feature
> +        Then  the contact should be deleted
and assert that the given user should be deleted. (the user should not be in the contact list anymore)

2022-10-17 03:57 UTC, kiranadh1452 requested changes

2022-10-17 03:57 UTC, kiranadh1452 commented on Features1/tests/features/deleteContact.feature
> +            |anusha  |anusha@gmail.com  |Professional|
```suggestion
        And the user has added the following contacts
            |name    |email             |contact-type|
            |samiksha|samiksha@gmail.com|Personal    |
            |anusha  |anusha@gmail.com  |Professional|
```

2022-10-17 04:26 UTC, kiranadh1452 requested changes

2022-10-17 04:26 UTC, kiranadh1452 commented on Features1/tests/features/deleteContact.feature
>          And the following user has been added to the contact list
```suggestion
        Given the user has navigated to the contact page
        And the following users have been added to the contact list
```

2022-10-17 04:26 UTC, kiranadh1452 commented on Features1/tests/features/deleteContact.feature
>          Then the  user with email "samiksha@gmail.com" should not  be in contact list anymore
```suggestion
        Then the user with email "samiksha@gmail.com" should not  be in contact list anymore
```

2022-10-17 04:26 UTC, kiranadh1452 commented on Features1/tests/features/deleteContact.feature
>          Then the  user with email "samiksha@gmail.com" should not  be in contact list anymore
```suggestion
        Then the  user with email "samiksha@gmail.com" should not be in contact list anymore
```

2022-10-17 06:13 UTC, SagarGi commented on Features1/tests/features/deleteContact.feature
> +
```suggestion
```

2022-10-17 06:13 UTC, SagarGi commented on Features1/tests/features/deleteContact.feature
> +                |Anusha  |Anusha@gmail.com   |9846000  |Personal    |
```suggestion
                |Name    |Email              |Phone    |Contact Type|
                |Samiksha|Samiksha@gmail.com |9846000  |Personal    |
                |Binita  |Binita@gmail.com   |984600110|Personal    |
                |Anusha  |Anusha@gmail.com   |9846000  |Personal    |
```

make its intendation same as below

2022-10-17 06:24 UTC, SagarGi approved these changes

2022-10-17 06:24 UTC, merged