Delete contact scenario created
SagarGi/FeatureFiles pull request #20
Opened 2022-10-13 15:10 UTC by ritaadhikari

### Description
Feature file deleteContact.feature for the delete contact feature and scenario created for delete contact.

### issues
https://github.com/SagarGi/FeatureFiles/issues/5

2022-10-13 15:14 UTC, SagarGi commented on Features2/tests/features/deleteContact.feature
> +    So I can unwanted contacts from the contacts saved
```suggestion
    So I can remove unwanted contacts
```

2022-10-13 15:14 UTC, SagarGi commented on Features2/tests/features/deleteContact.feature
> +        When the user clicks the  detete  button
after adding contact there wiil be 4 delete button how will you know which user is deleted?

2022-10-17 04:11 UTC, kiranadh1452 requested changes

2022-10-17 04:11 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +        | <name> |<Email>| <Phone>| <Contact  Type>|
This can be shifted to Background as there seems to be repetition in both scenarios.

2022-10-17 04:11 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +        | example2 | example2@gmail.com |3333333333|personal|
Format this table properly.

2022-10-17 04:11 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +        | example2 | example2@gmail.com |3333333333|personal|
Format this one as well

2022-10-18 03:22 UTC, kiranadh1452 requested changes

2022-10-18 03:22 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +    Background:
```suggestion
    So I can  remove unwanted contacts from the contacts saved
   
    Background:
```

2022-10-18 03:22 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +    Background:
```suggestion
    So I can  remove unwanted contacts from the contacts saved
   
    Background:
```

2022-10-18 03:22 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +
```suggestion
        Then the contact with  name "example@gmail.com" should be deleted
        But the coontact with email "example2@gmail.com" should be displayed

```

2022-10-18 03:22 UTC, kiranadh1452 commented on Features2/tests/features/deleteContact.feature
> +        Then the contact with  name with "<email>"  will be deleted
```suggestion
        Then the contact with  name with "<email>"  should be deleted
```

2022-10-18 03:38 UTC, kiranadh1452 approved these changes

2022-10-18 03:38 UTC, merged