scenario created for edit contact
SagarGi/FeatureFiles pull request #22
Opened 2022-10-13 16:02 UTC by ritaadhikari

### Description 
Feature file editContact.feature  of edit contact has been created and scenario for edit  contact feature has been created

###  issues
https://github.com/SagarGi/FeatureFiles/issues/6

2022-10-16 01:06 UTC, SagarGi commented on Features2/tests/features/editContact.feature
> +     Then the  contact details will be edited
you have created so many users and this scenario does not specify which user information to edit. Please make related one.

2022-10-17 03:46 UTC, kiranadh1452 requested changes

2022-10-17 03:46 UTC, kiranadh1452 commented on Features2/tests/features/editContact.feature
> +        | mnbv | mnvb@gmail.com | 098876677 | Professional |
Please use proper formatting for table so that it is more readable. 

And does this feature test needs us to create so many contacts ?

2022-10-17 05:44 UTC, kiranadh1452 requested changes
Your current flow only edits the email field. Try editing other fields as well.

2022-10-17 05:44 UTC, kiranadh1452 commented on Features2/tests/features/editContact.feature
> +     Background:
Provide some proper line spaces.

2022-10-17 05:44 UTC, kiranadh1452 commented on Features2/tests/features/editContact.feature
> +     And  the user changes the required info of email by "edited@gmail.com"
```suggestion
     And  the user changes the email to "edited@gmail.com"
```

2022-10-17 05:44 UTC, kiranadh1452 commented on Features2/tests/features/editContact.feature
> +     Then the  contact details will be edited of the contact "abcde"
```suggestion
     Then the email should be updated to "edited@gmail.om" for the contact "abcde" 
```

2022-10-17 06:50 UTC, kiranadh1452 requested changes

2022-10-17 06:50 UTC, kiranadh1452 commented on Features2/tests/features/editContact.feature
> +
Use indentation same as above.

2022-10-17 06:56 UTC, kiranadh1452 approved these changes

2022-10-17 06:56 UTC, merged