Registration Feature Commit
SagarGi/FeatureFiles pull request #25
Opened 2022-10-13 17:16 UTC by Dikshyapoudel12

# Description: 
This is a feature file of new user registration of the Contact Manager
## Issue link:
https://github.com/SagarGi/FeatureFiles/issues

2022-10-16 01:20 UTC, SagarGi commented on Features4/tests/feature/registration.feature
> +    Given the Register Account page was navigated
```suggestion
    Given the user has navigated to register account page
```

2022-10-16 01:20 UTC, SagarGi commented on Features4/tests/feature/registration.feature
> +    Then the ContactFox page should be navigated on WebUI
```suggestion
    Then the user should be navigated to home page
```

2022-10-16 01:20 UTC, SagarGi commented on Features4/tests/feature/registration.feature
> +    Then the popup message "<Message>" should seen
```suggestion
    Then the popup message "<Message>" should be displayed on the webUI
```

2022-10-16 01:20 UTC, SagarGi commented on Features4/tests/feature/registration.feature
> +    Then the popup message "<Message>" should seen
```suggestion
    Then the popup message "<Message>" should be displayed on the webUI
```

2022-10-19 03:24 UTC, kiranadh1452 requested changes

2022-10-19 03:24 UTC, kiranadh1452 commented on Features4/tests/feature/registration.feature
> +    When the user login with the following credentails
```suggestion
    When the user registers with the following credentials
```

2022-10-20 03:06 UTC, kiranadh1452 requested changes

2022-10-20 03:06 UTC, kiranadh1452 commented on Features4/tests/feature/registration.feature
> +Background:
```suggestion
    So that I can have access to the ContactFox Page

Background:
```

2022-10-20 03:06 UTC, kiranadh1452 commented on Features4/tests/feature/registration.feature
> +    Given the user has navigated to register account page
```suggestion
    Given the user has navigated to the register account page
```

2022-10-20 03:06 UTC, kiranadh1452 commented on Features4/tests/feature/registration.feature
> +    Then the user should be navigated to home page
```suggestion
    Then the user should be navigated to the home page
```

2022-10-20 03:07 UTC, kiranadh1452 approved these changes

2022-10-20 03:07 UTC, merged