added feature for adding contact
SagarGi/FeatureFiles pull request #28
Opened 2022-10-13 18:31 UTC by Salipa-Gurung

### Description
Created feature file for adding new contact with two scenario outline : adding contact with full details and adding contact without full details.
### Realted Issue : https://github.com/SagarGi/FeatureFiles/issues/4

2022-10-14 11:16 UTC, SagarGi commented on Features3/tests/features/addContact.feature
> +        Given User is logged in and navigated to Contact Fox page
make past tense

2022-10-14 11:16 UTC, SagarGi commented on Features3/tests/features/addContact.feature
> +        Then contact with name as "<name>", email as "<email>", phone as "<phone>" and contact type as "<contact-type>" should not be created
i think with email and name we can create a contact (no need of phone number) pleas check once manaully

2022-10-17 03:35 UTC, kiranadh1452 requested changes

2022-10-17 03:35 UTC, kiranadh1452 commented on Features3/tests/features/addContact.feature
> +
Please format this part for readability.

2022-10-17 03:35 UTC, kiranadh1452 commented on Features3/tests/features/addContact.feature
> +
Please format this part for readability.

2022-10-17 03:35 UTC, kiranadh1452 commented on Features3/tests/features/addContact.feature
> +            |||professional|
Same with this one as well. Formatting would make it easier the table data.

2022-10-17 03:35 UTC, kiranadh1452 commented on Features3/tests/features/addContact.feature
> +        Then validation error message as "Please include an '@' in the email address." should pop up in the input field
Try out multiple combinations, like invalid email, name, phone, etc. Let's not repeat a single case twice.
````
|name|email|phone|contact-type|
|abc|abcgmail.com|9801234567|personal|
|abc|abcgmail.com|9801234567|professional|

Here, both of these cover a single case of invalid email. So no need to have two data, single one would be good enough.
```

2022-10-17 03:35 UTC, kiranadh1452 commented on Features3/tests/features/addContact.feature
> +        Then validation error message as "Please include an '@' in the email address." should pop up in the input field
Try out multiple combinations, like invalid email, name, phone, etc. Let's not repeat a single case twice.
````
|name|email|phone|contact-type|
|abc|abcgmail.com|9801234567|personal|
|abc|abcgmail.com|9801234567|professional|

Here, both of these cover a single case of invalid email. So no need to have two data, single one would be good enough.
```

2022-10-17 06:58 UTC, kiranadh1452 approved these changes

2022-10-17 06:58 UTC, merged