Search contact feature by Dikshya
SagarGi/FeatureFiles pull request #30
Opened 2022-10-13 20:35 UTC by Dikshyapoudel12

# Description:
 This is a Gherkin file written for the Search Contact Feature.
## Issue:
https://github.com/SagarGi/FeatureFiles/issues/7

2022-10-14 15:27 UTC, SagarGi commented on Features4/tests/feature/Search.feature
> +Feature:
rewrite this feature as told

2022-10-17 03:52 UTC, kiranadh1452 requested changes

2022-10-17 03:52 UTC, kiranadh1452 commented on Features4/tests/feature/Search.feature
> +    Then Added Contact should be exists
Please reconsider this part.

2022-10-17 06:31 UTC, kiranadh1452 requested changes

2022-10-17 06:31 UTC, kiranadh1452 commented on Features4/tests/feature/Search.feature
> +    I want to search contact by contact name
```suggestion
    I want to search contact by name or email
```

2022-10-17 06:31 UTC, kiranadh1452 commented on Features4/tests/feature/Search.feature
> +        And the following contacts has been created
```suggestion
        And the following contacts have been created 
```

2022-10-18 04:18 UTC, kiranadh1452 approved these changes

2022-10-18 04:18 UTC, merged