Delete contact feature by Dikshya
SagarGi/FeatureFiles pull request #31
Opened 2022-10-13 20:39 UTC by Dikshyapoudel12

# Description:
 This is a Gherkin File written for the Delete Contact Feature in Contact Management App.
## Issue:
https://github.com/SagarGi/FeatureFiles/issues/5

2022-10-14 15:25 UTC, SagarGi commented on Features4/tests/feature/deletContact.feature
> +    Then Added Contact should be exists
i have told to use only given step in background

2022-10-14 15:25 UTC, SagarGi commented on Features4/tests/feature/deletContact.feature
> +    Then  the contact should be deleted
what if there is no data?

2022-10-17 06:12 UTC, kiranadh1452 requested changes

2022-10-17 06:12 UTC, kiranadh1452 commented on Features4/tests/feature/deletContact.feature
> +    I want to delet added Contact
```suggestion
    I want to delete added Contact
```

2022-10-17 06:12 UTC, kiranadh1452 commented on Features4/tests/feature/deletContact.feature
> +    And the user has been navigated to the home page
```suggestion
#  Assuming that the follwing user has been registerd
    Given the user has logged in with valid email address "deekshyap@gmail.com" and valid password "123456"
    And the user has been navigated to the home page
```

2022-10-17 06:12 UTC, kiranadh1452 commented on Features4/tests/feature/deletContact.feature
> +        But  the contact with email "abc@gmail.com" should appear in  the contact list.
```suggestion
        But  the contact with email "abc@gmail.com" should appear in the contact list.
```

2022-10-18 04:28 UTC, kiranadh1452 approved these changes

2022-10-18 05:46 UTC, merged