Edit contact feature file added
SagarGi/FeatureFiles pull request #32
Opened 2022-10-14 01:46 UTC by Samikshap85

### description
This PR adds the Edit contact feature  

### Issues
https://github.com/SagarGi/FeatureFiles/issues/6

2022-10-16 01:08 UTC, SagarGi commented on Features1/tests/features/editContact.feature
> +        And clicks on the "Edit" button , data is displayed on the edit contact form
you have created 2 users so 2 edit button is there which edit button would you click?

2022-10-16 01:10 UTC, SagarGi commented
@Samikshap85  rather thank making editing each scenario make a scenario that creates a single user and edit its information and like wise make multiple user and edit specific user data. it would be enough

2022-10-17 03:44 UTC, kiranadh1452 requested changes

2022-10-17 03:44 UTC, kiranadh1452 commented on Features1/tests/features/editContact.feature
> +            Then  the contact name should be updated
```suggestion
            Then  the contact name should be updated to "samiksha"
```

2022-10-17 03:44 UTC, kiranadh1452 commented on Features1/tests/features/editContact.feature
> +            Then  the contact phone should be updated
```suggestion
            Then  the contact phone should be updated to "98001000"
```

2022-10-17 03:44 UTC, kiranadh1452 commented on Features1/tests/features/editContact.feature
> +            Then  the contact type should be updated
```suggestion
            Then  the contact type should be updated to "Personal"
```

2022-10-17 03:44 UTC, kiranadh1452 commented on Features1/tests/features/editContact.feature
> +            Then the contact should be updated with the new data
Check if the new data is actually updated.

2022-10-17 03:44 UTC, kiranadh1452 commented on Features1/tests/features/editContact.feature
> +
```suggestion
```

2022-10-18 04:20 UTC, kiranadh1452 approved these changes

2022-10-18 04:20 UTC, merged