Search features added
SagarGi/FeatureFiles pull request #33
Opened 2022-10-14 02:15 UTC by Samikshap85

### description
>This PR adds search feature 

 ###Issues
https://github.com/SagarGi/FeatureFiles/issues/7

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +    Scenario: Search contacts with name or email address
may be search with only email because its unique

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            When the user enters"<name>" or email "<email>" present in the contact list
```suggestion
            When the user enters email "<email>" present in the contact list
```

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            Then the contact should be display
```suggestion
            Then the user with email <email> should be listed on in the contact list
```

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            When the user enters phone number as "phone"
may be provide number instead of "phone"

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            Then contacts shouldnot be displayed
```suggestion
            Then the user with phone "phone" should be listed on in the contact list
```

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            Given the user have navigated to the contact page and have the following contacts
break this step into two steps

2022-10-16 01:16 UTC, SagarGi commented on Features1/tests/features/searchContact.feature
> +            When the user enters different name  as "<name>" or different email as "<email>" from the following
how can user enter name and email at the same time. may be use email since its unique

2022-10-17 03:36 UTC, kiranadh1452 requested changes

2022-10-17 03:36 UTC, kiranadh1452 commented on Features1/tests/features/searchContact.feature
> +
Which contact should not be displayed?

2022-10-17 06:40 UTC, kiranadh1452 requested changes

2022-10-17 06:40 UTC, kiranadh1452 commented on Features1/tests/features/searchContact.feature
> +
```suggestion
```

2022-10-17 06:40 UTC, kiranadh1452 commented on Features1/tests/features/searchContact.feature
> +        When the user enters following email in the search input
Make this step such that it is reusable.

2022-10-18 03:45 UTC, kiranadh1452 requested changes
Let's reuse steps.

2022-10-18 03:45 UTC, kiranadh1452 commented on Features1/tests/features/searchContact.feature
> +        When the user enters following email in the search input
```suggestion
        When the user enters following data in the search input
```

2022-10-18 03:45 UTC, kiranadh1452 commented on Features1/tests/features/searchContact.feature
> +        When the user enters following email in the search input
```suggestion
        When the user enters following data in the search input
```

2022-10-18 04:19 UTC, kiranadh1452 approved these changes

2022-10-18 04:19 UTC, merged