delete contact susmita
SagarGi/FeatureFiles pull request #35
Opened 2022-10-14 08:51 UTC by susmitathapa

### Description
- In this feature file I have written scenarios for delete contact feature
### Related Issue
- https://github.com/SagarGi/FeatureFiles/issues/5

2022-10-14 15:20 UTC, SagarGi commented on Features5/tests/features/deleteContact.feature
> +     So that I can free up the space
```suggestion
     So that I can remove unwanted contacts from lists
```

2022-10-14 15:20 UTC, SagarGi commented on Features5/tests/features/deleteContact.feature
> +        |<name>  |<email>  |<phone>   |<contactType> |
```suggestion
        Given user has navigated to homepage
        And user has added following contacts:
        |name    |email    |phone     |contactType   |
        |<name>  |<email>  |<phone>   |<contactType> |
```

break this down like above and also to others feature file where you have used liked this

2022-10-14 15:20 UTC, SagarGi commented on Features5/tests/features/deleteContact.feature
> +        When user clicks "delete" button of following contact:
```suggestion
        When user deletes the following contact with email:
        |email|
        |<email>|
```

we can find the delete button from email i guess so no need to pass all the data

2022-10-14 15:20 UTC, SagarGi commented on Features5/tests/features/deleteContact.feature
> +        |Sita    |sita412@gmail.com    |          |Professional |
you have passed the data from example table (one row at a time). how can we see these data after deleing?

2022-10-17 04:24 UTC, kiranadh1452 requested changes

2022-10-17 04:24 UTC, kiranadh1452 commented on Features5/tests/features/deleteContact.feature
> +        |Gita    |sita412@gmail.com    |          |Professional |
```suggestion
           |name    |email                |phone     |contactType  |
           |Susmita |susmita412@gmail.com |984635346 |Personal     |
           |Sita    |sita412@gmail.com    |984635446 |Professional |    
           |Gita    |sita412@gmail.com    |          |Professional | 
```

2022-10-17 04:24 UTC, kiranadh1452 commented on Features5/tests/features/deleteContact.feature
> +
Please indent the table a little right. Looks more readable and distinct from other.

2022-10-17 06:26 UTC, SagarGi commented on Features5/tests/features/deleteContact.feature
> +   Scenario Outline: User wants to delete specific contact
```suggestion
   Scenario Outline: User deletes specific contact
```

2022-10-17 06:43 UTC, SagarGi approved these changes

2022-10-17 06:43 UTC, merged