edit contact feature file
SagarGi/FeatureFiles pull request #36
Opened 2022-10-14 09:45 UTC by susmitathapa

### Description
- In this feature file I have written scenario for edit contact feature.

## Related Issue
- https://github.com/SagarGi/FeatureFiles/issues/6

2022-10-14 15:13 UTC, SagarGi commented on Features5/tests/editContact.feature
> +Feature: edit contact
For this edit feature make a very simple feature file without any complex:
like 
make scenarios 1 as : make or add a single user and edit its data
make scenarios 2 as: make or add multiple user to contact and edit a specific user data by providing name or email

these two would be enough

2022-10-17 04:17 UTC, kiranadh1452 requested changes

2022-10-17 04:17 UTC, kiranadh1452 commented on Features5/tests/editContact.feature
> +        |name    |email    |phone     |contactType   |
```suggestion
        Given user has navigated to the homepage
        And the user has added the following contacts:
        |name    |email    |phone     |contactType   |
```

2022-10-17 04:17 UTC, kiranadh1452 commented on Features5/tests/editContact.feature
> +
This scenario would not work. The contact `Sita` would not be available in the contact list until the second example runs from the Example table. Rather not use Outline for this case.

2022-10-17 06:35 UTC, kiranadh1452 approved these changes

2022-10-17 06:35 UTC, merged