Refactor login
SagarGi/FeatureFiles pull request #57
Opened 2022-10-20 09:09 UTC by Samikshap85

###Description
>This PR adds refactoring of login feature where the user register first and then only logs in

2022-10-21 04:03 UTC, kiranadh1452 requested changes

2022-10-21 04:03 UTC, kiranadh1452 commented on Features1/tests/config.js
> +  global.browser = await chromium.launch({ headless: false, slowMo: 100 });
```suggestion
  global.browser = await chromium.launch();
```

2022-10-21 04:03 UTC, kiranadh1452 commented on Features1/tests/features/login.feature
> +    When  the user enters "demo@gmail.com" and "hello123"
These lines are differently indented.

2022-10-21 04:03 UTC, kiranadh1452 commented on Features1/tests/stepDefinitions/loginContext.js
> +
Why empty?

2022-10-21 04:41 UTC, kiranadh1452 requested changes

2022-10-21 04:41 UTC, kiranadh1452 commented on Features1/tests/stepDefinitions/loginContext.js
>      await page.pause();
Why page.pause() ?

2022-10-22 05:19 UTC, SagarGi commented on Features1/tests/features/login.feature
> +    And the user has been register with following user information
```suggestion
    And the user has been registered with following user information
```

2022-10-22 05:19 UTC, SagarGi commented on Features1/tests/features/login.feature
> +    When  the user enters "demo@gmail.com" and "hello123"
```suggestion
    When  the user login with email "demo@gmail.com" and password "hello123"
```

2022-10-23 05:50 UTC, SagarGi commented on Features1/tests/config.js
> +  global.browser = await chromium.launch({ headless: false, slowMo: 100 });
```suggestion
  global.browser = await chromium.launch({});
```

2022-10-23 05:50 UTC, SagarGi commented on Features1/tests/config.js
> +  global.browser = await chromium.launch({ headless: false, slowMo: 100 });
remove this then we can merge this.

2022-10-24 14:57 UTC, kiranadh1452 approved these changes

2022-10-24 14:57 UTC, merged