pageObject for login feature
SagarGi/FeatureFiles pull request #63
Opened 2022-10-31 10:02 UTC by susmitathapa

### Description
-This PR is related to implementation of page object model(POM) in login feature
-A new folder pageObjects is created

2022-10-31 10:06 UTC, kiranadh1452 commented
@susmitathapa 
This PR has unwanted file changes (there are changes in contact feature file and context which should not be the case). Fix that.

2022-10-31 10:06 UTC, kiranadh1452 commented
@susmitathapa 
This PR has unwanted file changes (there are changes in contact feature file and context which should not be the case). Fix that.

2022-10-31 10:10 UTC, kiranadh1452 requested changes
This PR has unwanted file changes (there are changes in contact feature file and context which should not be the case). Fix that.

2022-11-01 09:36 UTC, SagarGi commented on Features5/tests/pageObjects/loginPage.js
> +    //locators
```suggestion
    //selectors
```

2022-11-01 09:36 UTC, SagarGi commented on Features5/tests/pageObjects/loginPage.js
> +    await page.goto("http://localhost:3000");
put it to constructor

2022-11-01 09:36 UTC, SagarGi commented on Features5/tests/pageObjects/registrationPage.js
> +    await page.goto("http://localhost:3000");
.

2022-11-01 09:56 UTC, SagarGi commented on Features5/tests/stepDefinitions/userRegistrationContext.js
>      console.log("enters valid credentials");
remove this

2022-11-01 10:01 UTC, SagarGi approved these changes

2022-11-01 10:01 UTC, merged